DROP TABLE EMPLOYEE_ROLE;
CREATE TABLE EMPLOYEE_ROLE(
   employee_role_id   INT  NOT NULL PRIMARY KEY
  ,name               VARCHAR(255)
);

INSERT INTO EMPLOYEE_ROLE VALUES(1, 'Administrator');
INSERT INTO EMPLOYEE_ROLE VALUES(2, 'Modernator');
